CREATE TABLE [dbo].[PROJECT] (
    [PROJECT ID]       INT        NOT NULL,
    [PROJECT LOCATION] NCHAR (50) NOT NULL,
    [PROJECT NAME]     NCHAR (50) NULL,
    [CUSTOMERID]       INT        NOT NULL,
    PRIMARY KEY CLUSTERED ([PROJECT ID] ASC)
);

