//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOOLE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        public int PROJECT_ID { get; set; }
        public string PROJECT_LOCATION { get; set; }
        public string PROJECT_NAME { get; set; }
        public int CUSTOMERID { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
